name: main
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.1
      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 21
          registry-url: https://npm.pkg.github.com/
          scope: '@laufeymatth'
      - name: npm install
        run: npm i
      - name: publish 
        run: npm publish
        env: 
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}